### ISSUE TITLE
Publish release 2.0.1 to podspec repo master

### ISSUE THREAD

**Issue by diogoguimaraes** [theadam/SwiftClient#14]
Hi @theadam , 
Could you please publish the 2.0.1 release to the pod spec repo?
Should only be required to run the following command:
```Bash
pod trunk register <email> "name"
pod trunk push SwiftClient.podspec
``` 
I have tried to use the new version but the pod cannot be found:
```Bash
-> SwiftClient (2.0.0)
   A simple HTTP client library written in Swift 2
   pod 'SwiftClient', '~> 2.0.0'
   - Homepage: https://github.com/theadam/SwiftClient
   - Source:   https://github.com/theadam/SwiftClient.git
   - Versions: 2.0.0, 1.0.0 [master repo]
```
Thank you

**Comment by theadam** [comment]
Yes, this was supposed to happen with the tag, but i need to perform some updates on my laptop.  This will happen as soon as possible.

**Comment by theadam** [comment]
OK! got everything updated and did a push to cocoapods.  Let me know if everything looks good.  Im closing!

**Comment by diogoguimaraes** [comment]
Thank you very much @theadam !

**Comment by theadam** [comment]
No prob! sorry for the delay!
