### ISSUE TITLE
PodSpec Broken?

### ISSUE THREAD

**Issue by DavidGagne** [theadam/SwiftClient#20]
I've tried twice now to install this using CocoaPods and although the pod install feature says it's installed, I'm unable to "import SwiftClient" properly.
"Cannot load underlying module for SwiftClient"

**Comment by SandroMachado** [comment]
Hi @DavidGagne,

It is working here. I started a new project and tested it. 

# The pod file.
```
platform :ios, '9.0'

use_frameworks!

target 'test' do
    pod 'SwiftClient', '~> 2.0'
end
```
# The pod `Podfile.lock` generated.

```
PODS:
  - SwiftClient (2.0.3)

DEPENDENCIES:
  - SwiftClient (~> 2.0)

SPEC CHECKSUMS:
  SwiftClient: 8e30ede88d9fd0f15c425a0926efc5159368b3e1

COCOAPODS: 0.38.2

```

The screenshot of the application running using the pod file specified above.
![screen shot 2016-05-04 at 00 01 48](https://cloud.githubusercontent.com/assets/631739/15000985/b5e12aa0-118b-11e6-9537-5ce4d3d45b60.png)

**Comment by DavidGagne** [comment]
Hey @SandroMachado,
Thanks! I will try this. The readme doesn't include cocopod installation instructions, so I was just guessing at how to install it and didn't think to include the version in my podfile.
I'll try it again now.

**Comment by SandroMachado** [comment]
Hi @DavidGagne,

did it worked?

Regards

**Comment by DavidGagne** [comment]
Yes! It worked when I included the versioning.
Thanks!

**Comment by SandroMachado** [comment]
Great! 👍
