### ISSUE TITLE
how to get cookie from response by swiftclient？

### ISSUE THREAD

**Issue by pasicopan** [theadam/SwiftClient#6]
how to get cookie from response by swiftclient？
I need to get the token from the cookie,any help is appreciated

**Comment by pasicopan** [comment]
fix word

**Comment by theadam** [comment]
For a quick and dirty swift solution, this will get you going: 
```Swift
NSHTTPCookieStorage.sharedHTTPCookieStorage().cookiesForURL(NSURL(string: "MYDOMAIN")!)
```

If this does not work for you, you may also need to set the [cookie accept policy](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSHTTPCookieStorage_Class/index.html#//apple_ref/occ/instp/NSHTTPCookieStorage/cookieAcceptPolicy).

I'm not sure if I would want to have this functionality in SwiftClient api.  It seems overkill to add all cookies for a domain to every response, for example.  The only place id really want to see it is a separate cookie manager that just makes the NSHTTPCookieStorage api easier to use.  This can just as well be another project completely.  Does that sound reasonable to you?

**Comment by pasicopan** [comment]
It is very helpful，thanks a lot。
